SELECT
sub.CUSTOMER_ID,
sub.LANGUAGE_COUNTRY,
sub.EMAIL_ADDRESS
FROM
(
SELECT
a.CUSTOMER_ID,
a.LANGUAGE_COUNTRY,
a.EMAIL_ADDRESS,
row_number() OVER (PARTITION BY a.LANGUAGE_COUNTRY ORDER BY a.CUSTOMER_ID desc) as rowindex
FROM SUBDATA a
WHERE a.CUSTOMER_ID IN (SELECT SubscriberKey FROM ENT._Subscribers WHERE Status = 'Active')
) sub
WHERE rowindex = 1
